set -euo pipefail

export NCCL_P2P_DISABLE="1"
export NCCL_IB_DISABLE="1"

PROJECT_ROOT_GUESS="${GER_PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)}"
PYTHON_BIN="${GER_PYTHON:-${PROJECT_ROOT_GUESS}/.venv/bin/python}"
if [ ! -x "$PYTHON_BIN" ]; then
    PYTHON_BIN="${PYTHON:-python}"
fi

require_nonempty_file() {
    local file="$1"
    if [ ! -s "$file" ]; then
        echo "Required output file is missing or empty: $file" >&2
        exit 1
    fi
}

# Check if the first argument is provided and not empty
if [ "$#" -eq 1 ] && [ -n "$1" ]; then
    # Get YAML file path from the first argument
    YAML_FILE="$1"

    # Set environment variables by sourcing the commands generated by the Python script
    source <("$PYTHON_BIN" yaml_load.py "$YAML_FILE")
else
    echo "<<Warning>>: YAML file path is not provided or is empty. Please make sure that you have passed the required enviromental variables."
    exit 1
fi

PIPELINE_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${PIPELINE_SCRIPT_DIR}/icl_runtime_defaults.sh"
apply_icl_runtime_defaults
PROMPT_ICL="${GER_PROMPT_ICL:-$PROMPT_ICL}"

RETRIEVE_DIM="${RETRIEVE_DIM:-${GER_RETRIEVE_DIM:-128}}"
SUFFIX="${SUFFIX:-${GER_SUFFIX:-_8}}"
TEST_SUFFIX="${TEST_SUFFIX:-${GER_TEST_SUFFIX:-_8}}"
SENTENCE_RESULT_SUFFIX="${SENTENCE_RESULT_SUFFIX:-${GER_SENTENCE_RESULT_SUFFIX:-}}"
SENTENCE_RESULT_DIR="${SENTENCE_RESULT_DIR:-retrieved_icl_${MODEL_KEY}${SENTENCE_RESULT_SUFFIX}}"

RETRIEVED_EXAMPLES_DIR="${GER_RETRIEVED_EXAMPLES_DIR:-${SENTENCE_RESULT_DIR}/retrieved_examples_dim${RETRIEVE_DIM}${SUFFIX}${TEST_SUFFIX}}"
FINAL_RESULT_DIR="${GER_FINAL_RESULT_DIR:-${SENTENCE_RESULT_DIR}/final_retrieved_icl_dim${RETRIEVE_DIM}${SUFFIX}${TEST_SUFFIX}}"

INFERENCE_BATCH_SIZE="${GER_INFERENCE_BATCH_SIZE:-4}"
MAX_NEW_TOKENS="${GER_MAX_NEW_TOKENS:-512}"
SEED="${GER_SEED:-${SEED:-88}}"
DO_SAMPLE="${GER_DO_SAMPLE:-${DO_SAMPLE:-0}}"
TEMPERATURE="${GER_TEMPERATURE:-${TEMPERATURE:-0.0}}"
TOP_P="${GER_TOP_P:-${TOP_P:-1.0}}"
NUM_SHARDS="${GER_NUM_SHARDS:-1}"
SHARD_ID="${GER_SHARD_ID:-}"
SHARD_GPU_LIST="${GER_SHARD_CUDA_VISIBLE_DEVICES:-$CUDA_VISIBLE_DEVICES}"
DIALOGUE_ARGS=()
case "${DIALOGUE_FORM}" in
    1|true|True|TRUE|yes|Yes|YES)
        DIALOGUE_ARGS+=(--dialogue_form)
        ;;
esac
SAMPLE_ARGS=()
case "${DO_SAMPLE}" in
    1|true|True|TRUE|yes|Yes|YES)
        SAMPLE_ARGS+=(--do_sample)
        ;;
esac
DYNAMIC_EXAMPLE_ARGS=()
case "${DYNAMIC_EXAMPLE_NUM_ERROR}" in
    1|true|True|TRUE|yes|Yes|YES)
        DYNAMIC_EXAMPLE_ARGS+=(
            --dynamic_in_domain_example_num
            --dynamic_in_domain_example_min="$DYNAMIC_EXAMPLE_NUM_ERROR_MIN"
            --dynamic_in_domain_example_target_avg="$DYNAMIC_EXAMPLE_NUM_ERROR_TARGET_AVG"
        )
        ;;
esac

# conversion
RESULT_DIR=$FINAL_RESULT_DIR
IFS=':' read -r first_part second_part <<< "$DATASET"
TEST_DATASET_NAME=${first_part}

# delete old results
# rm -r $RESULT_DIR

if [ "$NUM_SHARDS" -gt 1 ] && [ -z "$SHARD_ID" ]; then
    IFS=',' read -r -a SHARD_GPUS <<< "$SHARD_GPU_LIST"
    if [ "${#SHARD_GPUS[@]}" -eq 0 ]; then
        echo "No GPUs found in SHARD_GPU_LIST=$SHARD_GPU_LIST"
        exit 1
    fi

    PROGRESS_STOP_FILE="${RESULT_DIR}/${TEST_DATASET_NAME}/.shards_progress.done"
    mkdir -p "$(dirname "$PROGRESS_STOP_FILE")"
    rm -f "$PROGRESS_STOP_FILE"

    pids=()
    monitor_pid=""
    use_setsid=0
    if command -v setsid >/dev/null 2>&1; then
        use_setsid=1
    fi

    cleanup_shards() {
        local exit_code="${1:-130}"
        trap - INT TERM
        echo "Stopping retrieved-ICL shard workers..." >&2
        touch "$PROGRESS_STOP_FILE" 2>/dev/null || true
        if [ -n "$monitor_pid" ]; then
            kill -TERM "$monitor_pid" 2>/dev/null || true
        fi
        for pid in "${pids[@]}"; do
            if [ "$use_setsid" -eq 1 ]; then
                kill -TERM "-$pid" 2>/dev/null || true
            else
                kill -TERM "$pid" 2>/dev/null || true
            fi
        done
        sleep 2
        for pid in "${pids[@]}"; do
            if [ "$use_setsid" -eq 1 ]; then
                kill -KILL "-$pid" 2>/dev/null || true
            else
                kill -KILL "$pid" 2>/dev/null || true
            fi
        done
        exit "$exit_code"
    }
    trap 'cleanup_shards 130' INT
    trap 'cleanup_shards 143' TERM

    for shard in $(seq 0 $((NUM_SHARDS - 1))); do
        gpu="${SHARD_GPUS[$((shard % ${#SHARD_GPUS[@]}))]}"
        echo "Launching retrieved-ICL shard ${shard}/${NUM_SHARDS} on GPU ${gpu}"
        if [ "$use_setsid" -eq 1 ]; then
            GER_DISABLE_CHILD_PROGRESS=1 GER_QUIET_CHILD_LOG=1 GER_SHARD_ID="$shard" GER_NUM_SHARDS="$NUM_SHARDS" GER_CUDA_VISIBLE_DEVICES="$gpu" setsid bash "$0" "$YAML_FILE" &
        else
            GER_DISABLE_CHILD_PROGRESS=1 GER_QUIET_CHILD_LOG=1 GER_SHARD_ID="$shard" GER_NUM_SHARDS="$NUM_SHARDS" GER_CUDA_VISIBLE_DEVICES="$gpu" bash "$0" "$YAML_FILE" &
        fi
        pids+=("$!")
    done
    echo "All ${NUM_SHARDS} retrieved-ICL shards launched in parallel; waiting for all shard workers."

    "$PYTHON_BIN" scripts/monitor_sharded_progress.py \
        --dir="${RESULT_DIR}/${TEST_DATASET_NAME}" \
        --num-shards="$NUM_SHARDS" \
        --desc="${TEST_DATASET_NAME} shards" \
        --stop-file="$PROGRESS_STOP_FILE" &
    monitor_pid="$!"

    status=0
    for pid in "${pids[@]}"; do
        wait "$pid" || status=1
    done
    touch "$PROGRESS_STOP_FILE"
    wait "$monitor_pid" || true
    trap - INT TERM
    if [ "$status" -ne 0 ]; then
        exit "$status"
    fi

    "$PYTHON_BIN" scripts/merge_sharded_predictions.py \
        --dir="${RESULT_DIR}/${TEST_DATASET_NAME}" \
        --num_shards="$NUM_SHARDS"
else
    SHARD_ID="${SHARD_ID:-0}"
    echo "Running retrieved-ICL shard ${SHARD_ID}/${NUM_SHARDS} with CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES} (pid $$)"
    CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" "$PYTHON_BIN" icl.py \
        --datasets="$DATASET" \
        --prompts="$PROMPT_ICL" \
        --trust_remote_code=true \
        --output_dir=$RESULT_DIR \
        --max_new_tokens="$MAX_NEW_TOKENS" \
        --postprocess="gec" \
        --model_name_or_path="$MODEL" \
        --in_domain_example_num=$EXAMPLE_NUM_ERROR \
        --cross_domain_example_num=$EXAMPLE_NUM_CORRECT \
        --in_domain_filter="error" \
        --cross_domain_filter="correct" \
        --in_domain_example_mode="default" \
        --cross_domain_example_mode="default" \
        --examples_dir="$RETRIEVED_EXAMPLES_DIR" \
        --inference_batch_size="$INFERENCE_BATCH_SIZE" \
        --num_shards="$NUM_SHARDS" \
        --shard_id="$SHARD_ID" \
        --seed="$SEED" \
        --temperature="$TEMPERATURE" \
        --top_p="$TOP_P" \
        "${DYNAMIC_EXAMPLE_ARGS[@]}" \
        "${SAMPLE_ARGS[@]}" \
        "${DIALOGUE_ARGS[@]}"

    if [ "$NUM_SHARDS" -gt 1 ]; then
        exit 0
    fi
fi

# add --bf16 if use bfloat16


# evaluate
"$PYTHON_BIN" evaluate_gec.py \
    --dir="${RESULT_DIR}/${TEST_DATASET_NAME}" \
    --dataset="${TEST_DATASET_NAME}" \
    --device="0"

require_nonempty_file "${RESULT_DIR}/${TEST_DATASET_NAME}/predictions.jsonl"
if [ "$TEST_DATASET_NAME" = "bea19" ]; then
    require_nonempty_file "${RESULT_DIR}/${TEST_DATASET_NAME}/bea19.txt"
    require_nonempty_file "${RESULT_DIR}/${TEST_DATASET_NAME}/bea19.zip"
    cp "${RESULT_DIR}/${TEST_DATASET_NAME}/bea19.txt" "${RESULT_DIR}/${TEST_DATASET_NAME}/${TEST_DATASET_NAME}-output-retokenized.txt"
else
    require_nonempty_file "${RESULT_DIR}/${TEST_DATASET_NAME}/${TEST_DATASET_NAME}-output-retokenized.txt"
fi
