from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ICLConfig:
    """
    Arguments which define the model and tokenizer to load.
    """
    output_dir: str = field(
        metadata={
            "help": "The output directory where the model predictions and checkpoints will be written."
        },
    )
    seed: int = field(default=88, metadata={"help": "Random seed that will be set at the beginning of training."})
    examples_dir: str = field(
        default=None,
        metadata={
            "help": "Directory containing precomputed GER retrieval.jsonl files."
        },
    )
    max_new_tokens: int = field(
        default=512,
        metadata={
            "help": ("Max new tokens generated by model.")
        }
    )
    inference_batch_size: int = field(
        default=1,
        metadata={
            "help": ("Batch size for local vLLM inference.")
        }
    )
    num_shards: int = field(
        default=1,
        metadata={
            "help": ("Number of data shards for parallel local inference.")
        }
    )
    shard_id: int = field(
        default=0,
        metadata={
            "help": ("Current shard id for parallel local inference.")
        }
    )
    in_domain_example_num: int = field(
        default=0,
        metadata={
            "help": ("The number of in-domain examples selected. In domain datasets are set in the `datasets` argument.")
        }
    )
    cross_domain_example_num: int = field(
        default=0,
        metadata={
            "help": ("The number of all-domain examples selected. The datasets are set in the `icl_datasets` argument or recognized automatically by the `datasets` argument.")
        }
    )
    dynamic_in_domain_example_num: bool = field(
        default=False,
        metadata={
            "help": ("Dynamically choose the number of loaded in-domain examples per item while keeping the dataset average near a target.")
        }
    )
    dynamic_in_domain_example_min: int = field(
        default=2,
        metadata={
            "help": ("Minimum loaded in-domain examples per item when dynamic_in_domain_example_num is enabled.")
        }
    )
    dynamic_in_domain_example_target_avg: float = field(
        default=8.0,
        metadata={
            "help": ("Target average loaded in-domain examples per item when dynamic_in_domain_example_num is enabled.")
        }
    )
    in_domain_example_mode: str = field(
        default='default',
        metadata={
            "help": ("Example selection mode of in-domain datasets.")
        }
    )
    cross_domain_example_mode: str = field(
        default='default',
        metadata={
            "help": ("Example selection mode of cross-domain datasets.")
        }
    )
    in_domain_filter: str = field(
        default='',
        metadata={
            "help": ("Example filter of in-domain datasets.")
        }
    )
    cross_domain_filter: str = field(
        default='',
        metadata={
            "help": ("Example filter of cross-domain datasets.")
        }
    )
    do_sample: bool = field(
        default=False,
        metadata={
            "help": ("Whether to use sampling or greedy decoding during generation.")
        }
    )
    top_k: Optional[int] = field(
        default=None,
        metadata={
            "help": ("Number of highest probability vocabulary tokens to keep for top-k filtering.")
        }
    )
    top_p: float = field(
        default=1.0,
        metadata={
            "help": ("Magnitude to filter tokens by probability (1.0 means no filtering).")
        }
    )
    temperature: float = field(
        default=0.,
        metadata={
            "help": ("Temperature to adjust the probability distribution of generated tokens.")
        }
    )
    postprocess: str = field(
        default='no',
        metadata={
            "help": ("Postprocess type for the final generated text.")
        }
    )
    dialogue_form: bool = field(
        default=False,
        metadata={
            "help": ("Conduct dialogue template to continue the text generation in dialogue-supported models.")
        } 
    )
    def to_dict(self):
        return dict(self.__dict__)
    
    def __post_init__(self):
        pass
