export NCCL_P2P_DISABLE="1"
export NCCL_IB_DISABLE="1"

# Check if the first argument is provided and not empty
if [ "$#" -eq 1 ] && [ -n "$1" ]; then
    # Get YAML file path from the first argument
    YAML_FILE="$1"

    # Set environment variables by sourcing the commands generated by the Python script
    source <(python yaml_load.py "$YAML_FILE")
else
    echo "<<Warning>>: YAML file path is not provided or is empty. Please make sure that you have passed the required enviromental variables."
fi

RESULT_DIR=$DIR_EXPLANATION_FROM_RANDOM_ICL

CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" python generate.py \
    --datasets="$DATASET_NAME" \
    --last_generation_dir=$RESULT_DIR_ICL_RANDOM \
    --last_generation_as="prediction:hypothesis" \
    --prompts="$PROMPT_EXPLANATION" \
    --trust_remote_code=true \
    --output_dir="$RESULT_DIR" \
    --max_new_tokens=512 \
    --postprocess="normal" \
    --model_name_or_path="$MODEL" \
    --dialogue_form \

# add --bf16 if use bfloat16
