set -euo pipefail

export NCCL_P2P_DISABLE="1"
export NCCL_IB_DISABLE="1"

PROJECT_ROOT_GUESS="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PYTHON_BIN="${GER_PYTHON:-${PROJECT_ROOT_GUESS}/.venv/bin/python}"
if [ ! -x "$PYTHON_BIN" ]; then
    PYTHON_BIN="${PYTHON:-python}"
fi

require_nonempty_file() {
    local file="$1"
    if [ ! -s "$file" ]; then
        echo "Required output file is missing or empty: $file" >&2
        exit 1
    fi
}

# Check if the first argument is provided and not empty
if [ "$#" -eq 1 ] && [ -n "$1" ]; then
    # Get YAML file path from the first argument
    YAML_FILE="$1"

    # Set environment variables by sourcing the commands generated by the Python script
    source <("$PYTHON_BIN" yaml_load.py "$YAML_FILE")
else
    echo "<<Warning>>: YAML file path is not provided or is empty. Please make sure that you have passed the required enviromental variables."
    exit 1
fi

PIPELINE_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${PIPELINE_SCRIPT_DIR}/icl_runtime_defaults.sh"
apply_icl_runtime_defaults
PROMPT_ICL="${GER_PROMPT_ICL:-$PROMPT_ICL}"

RETRIEVE_DIM="${RETRIEVE_DIM:-${GER_RETRIEVE_DIM:-128}}"
SUFFIX="${SUFFIX:-${GER_SUFFIX:-_8}}"
TEST_SUFFIX="${TEST_SUFFIX:-${GER_TEST_SUFFIX:-_8}}"
SENTENCE_RESULT_SUFFIX="${SENTENCE_RESULT_SUFFIX:-${GER_SENTENCE_RESULT_SUFFIX:-}}"
SENTENCE_RESULT_DIR="${SENTENCE_RESULT_DIR:-results_sentence_${MODEL_KEY}${SENTENCE_RESULT_SUFFIX}}"

DIR_RETRIEVE_BY_PROBING="${GER_DIR_RETRIEVE_BY_PROBING:-${DIR_RETRIEVE_BY_PROBING:-${SENTENCE_RESULT_DIR}/icl_deepseek_retrieve_by_probing_pgy_${RETRIEVE_DIM}${SUFFIX}${TEST_SUFFIX}}}"
RESULT_DIR_ICL_PROBING="${GER_RESULT_DIR_ICL_PROBING:-${RESULT_DIR_ICL_PROBING:-${SENTENCE_RESULT_DIR}/icl_deepseek_res_probing_pgy_${RETRIEVE_DIM}${SUFFIX}${TEST_SUFFIX}}}"

INFERENCE_BATCH_SIZE="${GER_INFERENCE_BATCH_SIZE:-4}"
MAX_NEW_TOKENS="${GER_MAX_NEW_TOKENS:-512}"
SEED="${GER_SEED:-${SEED:-88}}"
DO_SAMPLE="${GER_DO_SAMPLE:-${DO_SAMPLE:-0}}"
TEMPERATURE="${GER_TEMPERATURE:-${TEMPERATURE:-0.0}}"
TOP_P="${GER_TOP_P:-${TOP_P:-1.0}}"
NUM_SHARDS="${GER_NUM_SHARDS:-1}"
SHARD_ID="${GER_SHARD_ID:-}"
SHARD_GPU_LIST="${GER_SHARD_CUDA_VISIBLE_DEVICES:-$CUDA_VISIBLE_DEVICES}"
DIALOGUE_ARGS=()
case "${DIALOGUE_FORM}" in
    1|true|True|TRUE|yes|Yes|YES)
        DIALOGUE_ARGS+=(--dialogue_form)
        ;;
esac
SAMPLE_ARGS=()
case "${DO_SAMPLE}" in
    1|true|True|TRUE|yes|Yes|YES)
        SAMPLE_ARGS+=(--do_sample)
        ;;
esac
DYNAMIC_EXAMPLE_ARGS=()
case "${DYNAMIC_EXAMPLE_NUM_ERROR}" in
    1|true|True|TRUE|yes|Yes|YES)
        DYNAMIC_EXAMPLE_ARGS+=(
            --dynamic_in_domain_example_num
            --dynamic_in_domain_example_min="$DYNAMIC_EXAMPLE_NUM_ERROR_MIN"
            --dynamic_in_domain_example_target_avg="$DYNAMIC_EXAMPLE_NUM_ERROR_TARGET_AVG"
        )
        ;;
esac

# conversion
RESULT_DIR=$RESULT_DIR_ICL_PROBING
IFS=':' read -r first_part second_part <<< "$DATASET"
TEST_DATASET_NAME=${first_part}

# delete old results
# rm -r $RESULT_DIR

if [ "$NUM_SHARDS" -gt 1 ] && [ -z "$SHARD_ID" ]; then
    IFS=',' read -r -a SHARD_GPUS <<< "$SHARD_GPU_LIST"
    if [ "${#SHARD_GPUS[@]}" -eq 0 ]; then
        echo "No GPUs found in SHARD_GPU_LIST=$SHARD_GPU_LIST"
        exit 1
    fi

    PROGRESS_STOP_FILE="${RESULT_DIR}/${TEST_DATASET_NAME}/.shards_progress.done"
    mkdir -p "$(dirname "$PROGRESS_STOP_FILE")"
    rm -f "$PROGRESS_STOP_FILE"

    pids=()
    monitor_pid=""
    use_setsid=0
    if command -v setsid >/dev/null 2>&1; then
        use_setsid=1
    fi

    cleanup_shards() {
        local exit_code="${1:-130}"
        trap - INT TERM
        echo "Stopping probing ICL shard workers..." >&2
        touch "$PROGRESS_STOP_FILE" 2>/dev/null || true
        if [ -n "$monitor_pid" ]; then
            kill -TERM "$monitor_pid" 2>/dev/null || true
        fi
        for pid in "${pids[@]}"; do
            if [ "$use_setsid" -eq 1 ]; then
                kill -TERM "-$pid" 2>/dev/null || true
            else
                kill -TERM "$pid" 2>/dev/null || true
            fi
        done
        sleep 2
        for pid in "${pids[@]}"; do
            if [ "$use_setsid" -eq 1 ]; then
                kill -KILL "-$pid" 2>/dev/null || true
            else
                kill -KILL "$pid" 2>/dev/null || true
            fi
        done
        exit "$exit_code"
    }
    trap 'cleanup_shards 130' INT
    trap 'cleanup_shards 143' TERM

    for shard in $(seq 0 $((NUM_SHARDS - 1))); do
        gpu="${SHARD_GPUS[$((shard % ${#SHARD_GPUS[@]}))]}"
        echo "Launching probing ICL shard ${shard}/${NUM_SHARDS} on GPU ${gpu}"
        if [ "$use_setsid" -eq 1 ]; then
            GER_DISABLE_CHILD_PROGRESS=1 GER_QUIET_CHILD_LOG=1 GER_SHARD_ID="$shard" GER_NUM_SHARDS="$NUM_SHARDS" GER_CUDA_VISIBLE_DEVICES="$gpu" setsid bash "$0" "$YAML_FILE" &
        else
            GER_DISABLE_CHILD_PROGRESS=1 GER_QUIET_CHILD_LOG=1 GER_SHARD_ID="$shard" GER_NUM_SHARDS="$NUM_SHARDS" GER_CUDA_VISIBLE_DEVICES="$gpu" bash "$0" "$YAML_FILE" &
        fi
        pids+=("$!")
    done
    echo "All ${NUM_SHARDS} probing ICL shards launched in parallel; waiting for all shard workers."

    "$PYTHON_BIN" scripts/monitor_sharded_progress.py \
        --dir="${RESULT_DIR}/${TEST_DATASET_NAME}" \
        --num-shards="$NUM_SHARDS" \
        --desc="${TEST_DATASET_NAME} shards" \
        --stop-file="$PROGRESS_STOP_FILE" &
    monitor_pid="$!"

    status=0
    for pid in "${pids[@]}"; do
        wait "$pid" || status=1
    done
    touch "$PROGRESS_STOP_FILE"
    wait "$monitor_pid" || true
    trap - INT TERM
    if [ "$status" -ne 0 ]; then
        exit "$status"
    fi

    "$PYTHON_BIN" scripts/merge_sharded_predictions.py \
        --dir="${RESULT_DIR}/${TEST_DATASET_NAME}" \
        --num_shards="$NUM_SHARDS"
else
    SHARD_ID="${SHARD_ID:-0}"
    echo "Running probing ICL shard ${SHARD_ID}/${NUM_SHARDS} with CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES} (pid $$)"
    CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" "$PYTHON_BIN" icl.py \
        --datasets="$DATASET" \
        --prompts="$PROMPT_ICL" \
        --trust_remote_code=true \
        --output_dir=$RESULT_DIR \
        --max_new_tokens="$MAX_NEW_TOKENS" \
        --postprocess="gec" \
        --model_name_or_path="$MODEL" \
        --in_domain_example_num=$EXAMPLE_NUM_ERROR \
        --cross_domain_example_num=$EXAMPLE_NUM_CORRECT \
        --in_domain_filter="error" \
        --cross_domain_filter="correct" \
        --in_domain_example_mode="default" \
        --cross_domain_example_mode="default" \
        --examples_dir="$DIR_RETRIEVE_BY_PROBING" \
        --inference_batch_size="$INFERENCE_BATCH_SIZE" \
        --num_shards="$NUM_SHARDS" \
        --shard_id="$SHARD_ID" \
        --seed="$SEED" \
        --temperature="$TEMPERATURE" \
        --top_p="$TOP_P" \
        "${DYNAMIC_EXAMPLE_ARGS[@]}" \
        "${SAMPLE_ARGS[@]}" \
        "${DIALOGUE_ARGS[@]}"

    if [ "$NUM_SHARDS" -gt 1 ]; then
        exit 0
    fi
fi

# add --bf16 if use bfloat16


# evaluate
"$PYTHON_BIN" evaluate_gec.py \
    --dir="${RESULT_DIR}/${TEST_DATASET_NAME}" \
    --dataset="${TEST_DATASET_NAME}" \
    --device="0"

require_nonempty_file "${RESULT_DIR}/${TEST_DATASET_NAME}/predictions.jsonl"
if [ "$TEST_DATASET_NAME" = "bea19" ]; then
    require_nonempty_file "${RESULT_DIR}/${TEST_DATASET_NAME}/bea19.txt"
    require_nonempty_file "${RESULT_DIR}/${TEST_DATASET_NAME}/bea19.zip"
    cp "${RESULT_DIR}/${TEST_DATASET_NAME}/bea19.txt" "${RESULT_DIR}/${TEST_DATASET_NAME}/${TEST_DATASET_NAME}-output-retokenized.txt"
else
    require_nonempty_file "${RESULT_DIR}/${TEST_DATASET_NAME}/${TEST_DATASET_NAME}-output-retokenized.txt"
fi


run_score() {
    case "$TEST_DATASET_NAME" in
        "conll14")
            "$PYTHON_BIN" ../scripts/ger_new_table1.py clean-score-output \
                --output ${RESULT_DIR}/conll14/conll14.txt \
                --reference-m2 ${DATASETS_DIR}/multilingual_raw/EN-conll14st-test-data/noalt/official-2014.combined.m2
            "$PYTHON_BIN" evaluators/m2scorer/scripts/m2scorer.py ${RESULT_DIR}/conll14/conll14.txt ${DATASETS_DIR}/multilingual_raw/EN-conll14st-test-data/noalt/official-2014.combined.m2 | tee ${RESULT_DIR}/conll14/conll14.score
            ;;
        "bea19")
            echo "BEA-19 is a blind official-server dataset; generated bea19.txt/bea19.zip and skipped local scoring."
            ;;
        "wilocness")
            "$PYTHON_BIN" evaluators/m2scorer/scripts/m2scorer.py ${RESULT_DIR}/wilocness/conll14.txt ${DATASETS_DIR}/multilingual_raw/EN-conll14st-test-data/noalt/official-2014.combined.m2 | tee ${RESULT_DIR}/wilocness/conll14.score
            ;;
        "falko_merlin")
            "$PYTHON_BIN" ../scripts/ger_new_table1.py clean-score-output \
                --output ${RESULT_DIR}/falko_merlin/falko_merlin-output-retokenized.txt \
                --reference-m2 ${DATASETS_DIR}/multilingual_raw/DE-FALKO-MERLIN/fm-test.m2
            "$PYTHON_BIN" evaluators/m2scorer/scripts/m2scorer.py ${RESULT_DIR}/falko_merlin/falko_merlin-output-retokenized.txt ${DATASETS_DIR}/multilingual_raw/DE-FALKO-MERLIN/fm-test.m2 | tee ${RESULT_DIR}/falko_merlin/falko_merlin.score
            ;;
        "rulec")
            "$PYTHON_BIN" evaluators/m2scorer/scripts/m2scorer.py ${RESULT_DIR}/rulec/rulec-output-retokenized.txt ${DATASETS_DIR}/multilingual_raw/RU-RULEC/RULEC-GEC.test.M2 | tee ${RESULT_DIR}/rulec/rulec.score
            ;;
        "estgec")
            "$PYTHON_BIN" evaluators/m2scorer/scripts/m2scorer.py ${RESULT_DIR}/estgec/estgec-output-retokenized.txt ${DATASETS_DIR}/multilingual_raw/ET-estgec/Tartu_L1_corpus/test/test_m2.txt | tee ${RESULT_DIR}/estgec/estgec.score
            ;;
        "rogec")
            "$PYTHON_BIN" evaluators/m2scorer/scripts/m2scorer.py ${RESULT_DIR}/rogec/rogec-output-retokenized.txt ${DATASETS_DIR}/multilingual/rogec/test.m2 | tee ${RESULT_DIR}/rogec/rogec.score
            ;;
        "nlpcc18")
            require_nonempty_file "${RESULT_DIR}/nlpcc18/nlpcc18.score"
            ;;
        "kor_union")
            "$PYTHON_BIN" evaluators/m2scorer/scripts/m2scorer.py ${RESULT_DIR}/kor_union/kor_union-output-processed.txt ${DATASETS_DIR}/multilingual_raw/KR-Shared\ Dataset/Preprocessed/union/union_test.m2 | tee ${RESULT_DIR}/kor_union/kor_union.score
            ;;
        "qalb2014")
            "$PYTHON_BIN" evaluators/m2scorer/scripts/m2scorer.py ${RESULT_DIR}/qalb2014/qalb2014-output-processed.txt ${DATASETS_DIR}/multilingual_raw/AR-QALB-0.9.1/data/2014/test/QALB-2014-L1-Test.m2 | tee ${RESULT_DIR}/qalb2014/qalb2014.score
            ;;
        *)
            echo "Unknown dataset name: $TEST_DATASET_NAME"
            exit 1
            ;;
    esac
}

case "${GER_SCORE_BACKGROUND:-0}" in
    1|true|True|TRUE|yes|Yes|YES)
        SCORE_DONE_FILE="${RESULT_DIR}/${TEST_DATASET_NAME}/.score.done"
        SCORE_FAIL_FILE="${RESULT_DIR}/${TEST_DATASET_NAME}/.score.failed"
        SCORE_PID_FILE="${RESULT_DIR}/${TEST_DATASET_NAME}/.score.pid"
        SCORE_LOG_FILE="${RESULT_DIR}/${TEST_DATASET_NAME}/score.background.log"
        rm -f "$SCORE_DONE_FILE" "$SCORE_FAIL_FILE" "$SCORE_PID_FILE"
        export PYTHON_BIN RESULT_DIR TEST_DATASET_NAME DATASETS_DIR DATASET
        export SCORE_DONE_FILE SCORE_FAIL_FILE SCORE_LOG_FILE
        export -f require_nonempty_file run_score
        if command -v setsid >/dev/null 2>&1; then
            nohup setsid bash -c '
            set -euo pipefail
            if run_score >"$SCORE_LOG_FILE" 2>&1; then
                touch "$SCORE_DONE_FILE"
            else
                echo "score failed with exit code $?" >>"$SCORE_LOG_FILE"
                touch "$SCORE_FAIL_FILE"
                exit 1
            fi
            ' >/dev/null 2>&1 &
        else
            nohup bash -c '
            set -euo pipefail
            if run_score >"$SCORE_LOG_FILE" 2>&1; then
                touch "$SCORE_DONE_FILE"
            else
                echo "score failed with exit code $?" >>"$SCORE_LOG_FILE"
                touch "$SCORE_FAIL_FILE"
                exit 1
            fi
            ' >/dev/null 2>&1 &
        fi
        echo "$!" > "$SCORE_PID_FILE"
        echo "Scoring for ${TEST_DATASET_NAME} is running in background with pid $(cat "$SCORE_PID_FILE")."
        ;;
    *)
        run_score
        ;;
esac
